### ISSUE TITLE
Engine related api's not working

### ISSUE THREAD

**Issue by victorperin** [eXigentCoder/krpc-node#18]
I can't access any engine related api. In the code example i try testing if the first received engine is active.

```js
    const vessel = await client.send( spaceCenter.getActiveVessel() )

    const parts = await vessel.parts.get()
    const engines = await parts.engines.get();

    await engines[0].active.get()  // throws error
```
or even:
```js
    const vessel = await client.send( spaceCenter.getActiveVessel() )

    const parts = await vessel.parts.get()
    const engines = await parts.engines.get();

    await client.send( spaceCenter.engineGetActive(engines[0].id) ) // throws error
```

```
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: Error receiving message
Instance not found
    at onMessage (C:\dev\kerbal-automations-in-js\node_modules\krpc-node\lib\client.js:384:25)
    at WebSocket.client.rpc.socket.onmessage (C:\dev\kerbal-automations-in-js\node_modules\krpc-node\lib\client.js:278:9)
    at WebSocket.onMessage (C:\dev\kerbal-automations-in-js\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:209:13)
    at Receiver._receiver.onmessage (C:\dev\kerbal-automations-in-js\node_modules\ws\lib\websocket.js:137:47)
    at Receiver.dataMessage (C:\dev\kerbal-automations-in-js\node_modules\ws\lib\receiver.js:397:14)
    at Receiver.getData (C:\dev\kerbal-automations-in-js\node_modules\ws\lib\receiver.js:347:12)
    at Receiver.startLoop (C:\dev\kerbal-automations-in-js\node_modules\ws\lib\receiver.js:143:16)
    at Receiver.add (C:\dev\kerbal-automations-in-js\node_modules\ws\lib\receiver.js:117:10)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
Emitted 'error' event at:
    at popCallback (C:\dev\kerbal-automations-in-js\node_modules\krpc-node\lib\client.js:406:28)
    at onMessage (C:\dev\kerbal-automations-in-js\node_modules\krpc-node\lib\client.js:386:16)
    at WebSocket.client.rpc.socket.onmessage (C:\dev\kerbal-automations-in-js\node_modules\krpc-node\lib\client.js:278:9)
    [... lines matching original stack trace ...]
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17) {
  dotNetStackTrace: '  at KRPC.Service.ObjectStore.GetInstance (UInt64 id) [0x00000] in <filename unknown>:0 \r\n' +
    '  at KRPC.Server.ProtocolBuffers.Encoder.Decode (Google.Protobuf.ByteString value, System.Type type) [0x00000] in <filename unknown>:0 \r\n' +
    '  at KRPC.Server.ProtocolBuffers.MessageExtensions.ToMessage (KRPC.Schema.KRPC.Argument argument, System.Type type) [0x00000] in <filename unknown>:0 \r\n' +
    '  at KRPC.Server.ProtocolBuffers.MessageExtensions.ToMessage (KRPC.Schema.KRPC.ProcedureCall call) [0x00000] in <filename unknown>:0 \r\n' +
    '  at KRPC.Server.ProtocolBuffers.MessageExtensions.ToMessage (KRPC.Schema.KRPC.Request request) [0x00000] in <filename unknown>:0 \r\n' +
    '  at KRPC.Server.WebSockets.RPCStream.Read (KRPC.Service.Messages.Request& request, System.Byte[] data, Int32 offset, Int32 length) [0x00000] in <filename unknown>:0 \r\n' +
    '  at KRPC.Server.Message.RPCStream.Poll () [0x00000] in <filename unknown>:0 \r\n' +
    '  at KRPC.Server.Message.RPCStream.get_DataAvailable () [0x00000] in <filename unknown>:0 \r\n' +
    '  at KRPC.Core.PollRequests (IList`1 yieldedContinuations) [0x00000] in <filename unknown>:0 '
}
```

PS: i can't even prevent this with a try-catch wrapping the active call.

**Comment by victorperin** [comment]
I've been digging for a while and discovered that #17 seems to fix. The most bizarre is, after stopped coding for a while and now i couldn't get the same error. seems to be something I must done wrong somewhere else and didn't find. :)

**Comment by eXigentCoder** [comment]
My apologies, I got married and was on honeymoon so have been off the radar for a bit!

Don't worry that type of thing happens to me all the time lol. Merging in #17 now and should be published shortly!
